spring:
  application:
    name: starvestop
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  payment:
    base-url: https://api.tosspayments.com/v1/payments
    secret-key: ${PAYMENT_SECRET_KEY}
kakao:
  oauth:
    client: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
    redirect: ${REDIRECT_URI}