name: Ci

on:
  pull_request:
    branches:
      - feat/cicd/test
    paths:
      - "backend/**"
      - "build.gradle"
      - "settings.gradle"
      - "gradle/**"
      - "gradlew"
      - "gradlew.bat"
      - ".github/workflows/ci.yml"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: make executable gradlew
        working-directory: backend
        run: chmod +x ./gradlew

      - name: run unittest
        working-directory: backend
        run: |
          ./gradlew clean test